### PR TITLE
Remove redundant code

### PR DESCRIPTION
**Pull request by itaisteinherz**
It has already been implemented in sindresorhus/got#584. (like #34, this PR is identical to sindresorhus/gh-got#32)

### CODE REVIEW

**Comment by itaisteinherz** [comment]
@hbetts you are correct. Let's put this on hold until the next version of `got` is released (and then I'll bump its version as well).

**Comment by itaisteinherz** [comment]
[`got` v9.2.0](https://github.com/sindresorhus/got/releases/tag/v9.2.0) has been released 🎉 I've bumped its minimum version. @hbetts can this be merged now?

**Comment by itaisteinherz** [comment]
Ping @hbetts @rarkins

**Comment by hbetts** [comment]
@itaisteinherz I was able to merge your change, but I won't be able to publish your change for about 8 or so hours (I don't have access to what I need to publish the change).

**Comment by hbetts** [comment]
Version 9.0.1 has been published with this refactor.

**Pull request merged**
